###===== user api=====

### get user api endpoint
GET http://localhost:8000/api/v1/users

### register user api endpoint
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "name" : "Roshan Doe",
    "email": "roshan@doe.com",
    "password": "123456"
}

### login user api endpoint
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
   "email": "jan@doe.com",
    "password": "123456"
}







#==== expenses api =====#
### get expenses 
GET http://localhost:8000/api/v1/expenses


### POST expenses 
POST http://localhost:8000/api/v1/expenses
Content-Type: application/json
Authorization: 628ea9b64550a42b7b4decfc

{
    "name": "Food",
    "amount": 100,
    "date": "2020-01-01"
}


### DELETE expenses 
DELETE http://localhost:8000/api/v1/expenses